README.md

Sorry, I remembered about this after submitting the PR and I didn't finish it in time for your review.

instructions on recovering cloudmaster from map deadlock

---

README.md
bin/update.py
salt/auto_update/init.sls
salt/base_prereqs.sls
salt/cfrjanitor/cfr_secrets.bash
salt/cfrjanitor/cfrjanitor.bash
salt/cfrjanitor/init.sls
salt/flashlight/init.sls
salt/install_from_release.sls
salt/peerscanner/init.sls
salt/top.sls
salt/waddell/init.sls

This is deployed and working fine in aranhoide's test cloudmaster.

Add cloudfront janitor to cloudmaster

---

salt/fallback_proxy/check_vultr_transfer.py
salt/fallback_proxy/util.py

The change itself is small.  I made a minor refactoring too, removing a function that wasn't pulling its weight anymore.  Even that doesn't add much.

retire servers over 95% bandwidth quota

---

salt/fallback_proxy/util.py

otherwise a server won't be retired if it's been split before, as seems probable.

use different flag file for retiring

---

salt/cloudmaster/init.sls

Fixes the errors creating some files (issue #54)

Fix for #54

---

bin/launch_cloudmaster.py

Removed undefined and unnecessary function from script

Fix launch_cloudmaster.py

---

salt/fallback_proxy/init.sls
salt/fallback_proxy/remap.config

It's a non-perfect but rather simple solution to fix https://github.com/getlantern/lantern/issues/3147.
Tested on the sandbox salt env.
@aranhoide Would you mind take a look?

add remap rule fixes lantern#3147

---

salt/fallback_proxy/records.config

@myleshorton @aranhoide This is the changes we discussed in email.
I applied the new configuration to 45.32.249.51 manually. Let's keep it running for a few hours and see if works!
`lsof -nPp 9291 | grep ESTAB | cut -d ">" -f 2 | cut -d ":" -f 1 | sort | uniq -c | sort -nk 1`

Adjust ATS network parameters

---

bin/config.py
bin/update.py
bin/util.py
salt/http_proxy/init.sls
salt/http_proxy/install_http_proxy.py
salt/http_proxy/install_http_proxy.sh

Please pull secrets repo and `git submodule update --remote` first.
I tried testing it on sandbox cloudmaster + minion, but it always failed to install packages.
> WARNING: The following packages cannot be authenticated!
>   unzip zip
> There are problems and -y was used without --force-yes

Download http-proxy-lantern v0.0.3 from private repo

---

salt/http_proxy/install_http_proxy.py

This grabs the analytics changes for getlantern/lantern#3409

Pointing at newest release of http-proxy-lantern

---

salt/http_proxy/init.sls
salt/http_proxy/rc.local

I'm going to go ahead and merge this so that I can test (don't know of another way to do it).

Setting txqueuelen and tcp_max_syn_backlog

---

salt/cloudmaster/refill_srvq.py

Store VPSs in blocked IPs in a quarantine set, instead of using them to serve users.  Flush the quarantine into the destroy queue when we don't have any pending or ongoing requests.

quarantine blocked IPs

---

salt/http_proxy/config.ini
salt/http_proxy/http-proxy.conf
salt/http_proxy/init.sls
salt/http_proxy/install_http_proxy.py

Also use config.ini to supply options.

Http proxy v0.0.10

---

salt/check_disk/check_disk.py
salt/check_disk/init.sls
salt/top.sls

Implements https://github.com/getlantern/lantern_aws/issues/97

alert on high disk usage; delete big logs and reboot if disk full

---

salt/http_proxy/config.ini
salt/http_proxy/fallback.json
salt/http_proxy/init.sls
salt/http_proxy/save_access_data.py

I've moved these changes into branch + PR like I should have

Added obfs4 support (don't merge yet)

---

salt/netdata/init.sls
salt/netdata/install-netdata.bash
salt/netdata/netdata.conf
salt/top.sls

Tested in my test cloudmaster.

add netdata support; enable in all VPSs

---

salt/cloudmaster/refill_srvq.py

Ugly, but should be short-lived, since the change to config server et al should be quick.

avoid breaking config server et al while in transition

---

salt/security.sls

Fixes https://github.com/getlantern/secret_lib/issues/9

disable password authentication

---

lib/vps_util.py
salt/cloudmaster/refill_srvq.py

This was created to fix some cert issues.  It's probably wise to keep these around, so if we have any similar problems in the future they're faster to fix.
The only tricky part about this is that some refactoring was done to share some logic with refill_srvq.py.  I have checked that launching proxies works alright with this new factoring.
This is not urgent, but preventing branch rot would be nice.

utilities to fix access_data/cfg issues; related refactoring

---

.gitignore
README.md
requirements.txt

@aranhoide So here's the simple PR

add requirements.txt resolve #138

---

bin/update.py
bin/util.py
salt/http_proxy/config.ini
salt/http_proxy/init.sls

This activates basic and anonymous, traffic reporting to a secondary Redis.

Send Redis reports to a secondary Redis

---

lib/misc_util.py

Fixes #145.  
Tested locally:
- IP permanently whitelist,
- no such IP in whitelist,
- key with lower ttl than the one being set, and
- key with higher ttl than the one being set.

whitelist should never reduce ttl

---

bin/update.py
salt/top.sls

@oxtoacart has a good test subject but it's in a production cloudmaster.  Quickest way to test this is to merge it!

first shot at fixing issue158

---

lib/vps_util.py
salt/http_proxy/util.py

minor refactoring and utility function

---

README.md
bin/config.py
bin/update.py
bin/util.py

Some of these are actually required to launch new cloudmasters, in any Salt version.

changes required to upgrade salt to v2015.8.8.2

---

etc/device_tx_analysis.py

Want to take a look at this @aranhoide ?
This python code might have some nice improvements that you can easily spot.

Plot device bandwidth

---

README.md

Add note about git-lfs pull origin master

---

lib/vps_util.py
salt/cloudmaster/init.sls
salt/cloudmaster/refill_srvq.py
salt/http_proxy/fallback.json
salt/http_proxy/init.sls
salt/http_proxy/save_access_data.py
salt/proxy_ufw_rules/init.sls
salt/proxy_ufw_rules/ufw_rules

I've tested that manually configuring the proxy_port and obfs4_port has the desired effect after running state.highstate on the proxy.  I've also added the code in refill_srvq.py to randomize the configuration for new proxies, but for the life of me I couldn't figure out how to get something into the queue that the script would read.  @aranhoide do you mind testing that piece of it?
cc: @myleshorton

Add randomization of proxy protocol and port
