getlantern/lantern_aws

- salt/fallback_proxy/remap.config
This will prevent ATS from appending port to "Host" HTTP Header. Fixes https://github.com/getlantern/lantern/issues/3147, again.
As it affects very few sites, it's ok to merge and deploy with other changes.
> ATS config updates

- salt/monitor/collectd.conf
It increased the collect interval to 15 minutes, and removed lots of measurements we didn't present for now, to prevent InfluxDB from explosion.
> reduce the data points of collectd

- salt/fallback_proxy/convcert.sh
- salt/fallback_proxy/init.sls
- salt/fallback_proxy/install_http_proxy.sh
v0.0.2 includes @uaalto 's fixes to eliminate the infinite loop to localhost. The changes didn't break Apache mimicking, I just tweaked the test code a bit to stop it from hanging, ref PR https://github.com/getlantern/http-proxy-lantern/pull/8.
@myleshorton and @aranhoide, as per our discussion in stand up, it's probably ok to deploy to Vultr?
> use http-proxy v0.0.2

- salt/http_proxy/install_http_proxy.py
I didn't notice the existence of this specific GitHub API endpoint. It's simpler than I thought.
> fetch http-proxy by tag

- bin/update.py
- bin/util.py
- salt/http_proxy/http-proxy.conf
- salt/http_proxy/init.sls
http-proxy already has `-logglytoken` option, this PR supply our own token when running it.
> supply loggly token to http-proxy

- salt/http_proxy/install_http_proxy.py
I tested by running `sudo salt "*" state.highstate` from cm-vltok1fffw. It updates correctly. Run Lantern valencia with fp-vltok1fffw-20151121-002 for a while and found no issue. Especially, http://photobucket.com/ and http://zh.moegirl.org/%E4%B8%9C%E6%96%B9Project render correctly.
@uaalto do you have any objection to deploy new version?
> upgrade http-proxy to v0.0.5

- salt/http_proxy/install_http_proxy.py
Occasionally, we get `text file busy` errors when trying to start the http-proxy service.  I've noticed this once after upgrading the http-proxy-lantern release.  I suspect there's something dangerous about updating the binary of a service while it's running.  I remember we used to stop the old (flashlight, peerscanner, ...) services before updating them, for this reason.
> stop http-proxy before updating its binary

- lib/retire_blocked_ips_cache.py
- lib/vultr_util.py
Updates to the caching code used by retire_blocked_ips, to support country-specific request stats.
Also sneaked in: retry some 10 times when Vultr server_list(None) returns the empty list.
> Country specific req stats

- salt/base_prereqs.sls
- salt/http_proxy/init.sls
- salt/stats/init.sls
- salt/stats/save_stats.py
- salt/top.sls
It's useful to have these on the VPS itself for manual inspection.  Curnently our Influx DB records data less often, keeps less of a history of it, and VPSs are more likely to be unable to hit influx for any reason than to run this cron job.
> save last week's load_avg/CPU/mem/network/... stats once a minute

- lib/redis_util.py
- lib/vps_util.py
This also begins with our policy of logging every operation that might be
interesting for diagnosing purposes, and in particular any op that mutates our
redis DB.
> utilities to make it more convenient to retire a server

- bin/config.py
- lib/fetchcfg.py
- lib/vps_util.py
- salt/check_vpss/check_vpss.py
- salt/cloudmaster/init.sls
The transition plan is:
- shut down all services in existing cloudmasters
- back up the redis DB
- run a script to transition the redis DB
- deploy this to all cloudmasters (this restarts services with the new config)
> move 'etc' to donyc3, assign its current cloudmasters to 'ir'

- salt/http_proxy/init.sls
Fixed an issue sending X-Lantern-Config-Client-IP header
Use Go's default cipher suites in tlsdefaults
Built with Go 1.5.3
Tested salt deployment on fp-vltok1fffw-20151121-002.
@aranhoide Do you think it's okay to deploy another round in production? I can also run the deployment with your instructions.
> update http-proxy to v0.0.13

- salt/lantern_build_prereqs/init.sls
The only thing for which we're currently using Java is for generating certs in proxies.  I have launched a new proxy from this branch and it passed the checkfallbacks test.
The main impetus for this is that Java 8 makes building ops-panel easier.  I'm getting [permgen errors](https://github.com/boot-clj/boot/wiki/JVM-Options#permgen-errors-java-7) while doing this.  While there are workarounds for that, it seems simplest to just upgrade to a Java version without this problem.
> upgrade to java 8

- lib/do_util.py
- lib/vps_util.py
- lib/vultr_util.py
- salt/checkfallbacks/init.sls
- salt/cloudmaster/refill_srvq.py
This requires a new request format.  Instead of requesting just a number, this now takes a JSON data structure with the following parameters:
```
{
"id": 6,
"obfs4_port": 62443,
"srvq": "donyc3ox:srvq:manual",
}
```
id - this is the same as the number that we used to send.
obfs4_port - optional port for launching an obfs4 proxy instead of an https proxy.  This should always be 62443.
srvq - the queue to which the successful launch response is sent.  This used to always go to the same queue, but now client can specify it.
> Added support for launching obfs4 proxies from srvreqq (incompatible with current configserver)

- lib/alert.py
- salt/sshalert/sshalert.py
If you accidentally ssh into a proxy, you'll be prompted to use hussh instead.  You can still override this if you're in a rush to fix something or you can't set up hussh at this moment.
For interactive logins, you just get asked to confirm that you really want to log in.  For noninteractive logins, you can prepend `_force_` to bypass this check.  In either case, the script will try and shame you on that. :)
As a side feature, ssh alerts now go to a new #ssh-alert slack channel.
I've tested this in a test proxy.
> ssh-alert doublecheck

- lib/do_util.py
- lib/vps_util.py
- salt/cloudmaster/init.sls
- salt/cloudmaster/launch_config_server.py
- salt/cloudmaster/refill_srvq.py
- salt/config_server/config-server.conf
- salt/config_server/init.sls
- salt/salt_cloud/cloud.profiles
- salt/top.sls
As of this writing, the uberjar itself needs to be manually built and uploaded to the cloudmaster, then you need to call highstate on the cloudmaster itself before launching/updating config servers.
Launch a config server by calling `launch_config_server.py` as root.  After that, you'll need to manually add it to the Cloudflare round robin.
This is as much automation as made sense for a first shot at launching some 2-8 config servers.
> Partial configuration for Digital Ocean-based config servers

- lib/misc_util.py
- salt/base_prereqs.sls
For some reason, timeout didn't work in subprocess.check_output when SSHing
into a site that demands a password.
This is needed by secret_lib.interactive_offload.
Tested by using it there.  I also tested that pushing this to my test
cloudmaster worked fine and that subprocess32 could be imported there
afterwards.
> fix parallel SSH

- salt/config_server/config-server.conf
I tested this by manually applying this config to a single config-server in production. The server came up correctly and /proc/<pid>/limits showed the right file descriptor limit. Curling my config from that server succeeded as well.
> Bumped up file descriptor limit on config-server

- lib/alert.py
- lib/model.py
- lib/vps_util.py
- salt/cloudmaster/retire.py
- salt/pylib/model.py
- salt/vps_sanity_checks/init.sls
- salt/vps_sanity_checks/vps_sanity_checks.py
This is **not** a real fix for https://github.com/getlantern/lantern_aws/issues/176, but it should reduce the harm it causes to users while we fix it, and it will serve as a continuous regression check afterwards. 
- Check that all entries in `srv->cfg` correspond to existing proxies.  Remove all `srv->cfg` (and related) entries where this is not true.  
- Check that the configs in redis match the ones in their local access_data.
- Alert to slack for failures in any of the above.
- Change sanity checks in general to be run every 1/2h.  I used to think this was too expensive, but I've fund that our production redis DB deals fine with this.
> Srv2cfg sanity checks

- lib/vps_util.py
- salt/cloudmaster/offload.py
Fixes #196.
These may happen as a result of normal ops and perhaps other (already ticketed) inconsistencies.
> make offloadq robust to no longer existing proxies

- salt/stats/init.sls
- salt/stats/stats.py
Test a new way to detect whether a machine is overloaded.  cpu_io is observed primarily, and I'm also reporting swap_tx, should that help confirm our suspicions that a proxy is overloaded.
This will do nothing but report to #staging-alerts ATM, but if it proves a good predictor I'll incorporate this check in the upcoming auto-offload/split PR.
> overload check

- bin/update.py
- bin/util.py
- salt/sshalert/init.sls
- salt/sshalert/sshalert.py
Not the most important issue but I got enough of a head start on this when redis was down that I thought I'd just go ahead and end this big PITA that is hussh/redis whitelisting, especially in test cloudmasters.
This change makes all VPSs check for whitelisted IPs by calling an endpoint in our ops panel.  If our ops panel is down, the user will be assumed to be whitelisted.
To whitelist yourself in the ops panel, just log into `ops.panel.io` with your github account.  If you are a member of the getlantern organization, your IP will get whitelisted.  Note that you need to give your app permission to see your membership (the membership of some Lantern devs is not public).
If you leave the `ops.panel.io` tab open, it will keep whitelisting your IP even if it changes.  Useful if you're …
> make sshalert.py ask the ops panel instead of redis
